### PR TITLE
fix: Remove `bottle :unneeded` which is deprecated

### PR DESCRIPTION
**Pull request by technicalpickles**
Fixes https://github.com/tophat/homebrew-bar/issues/48

### CODE REVIEW

**Comment by technicalpickles** [comment]
I've tried updating the the title, but semantic pull request is still unhappy. It also doesn't seem like builds kicked off 🤔

**Comment by technicalpickles** [comment]
Anything I can do to help get this merged?

**Comment by flood4life** [comment]
@technicalpickles as a workaround for the semantic build check not restarting you could either open a new PR or, say, reword your commit message and do a force push - that should trigger a new build too.

**Comment by technicalpickles** [comment]
@flood4life good call, should be fixed now.

**Comment by flood4life** [comment]
@iamogbz we'd appreciate a quick look at this when you have the time 🙏

**Comment by Sytten** [comment]
Can this be merged now?

**Pull request merged**
